name: Build exe

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v2.1.0
    - name: Print Versions
      run: |
        python --version
        pip --version
    - name: Install requirements
      run: |
        pip install pyinstaller
    - name: Run PyInstaller
      run: |
        python -m PyInstaller power-profiler.spec
    - name: See dist directory
      run: ls dist
    - uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: dist/typer.exe

