name: Build exe

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v2.1.0
    - name: Print Versions
      run: |
        python --version
        pip --version
        poetry --version
    - name: Install the package
      run: |
        poetry install --no-interaction --no-root --no-dev
    - name: Install PyInstaller
      run: |
        poetry run pip install pyinstaller
    - name: Run PyInstaller
      run: |
        poetry run python -m PyInstaller src\typer.py -F --clean -w
    - name: See dist directory
      run: ls dist
    - uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: dist/typer.exe

